[package]
name = "bebok-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
blake3.workspace = true
dirs.workspace = true
flate2.workspace = true
futures.workspace = true
globset.workspace = true
ignore.workspace = true
notify.workspace = true

bebok-llm = { path = "../bebok-llm" }
bebok-mcp = { path = "../bebok-mcp" }
bebok-skills = { path = "../bebok-skills" }
bebok-tools = { path = "../bebok-tools" }

regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
thiserror.workspace = true

tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
zip.workspace = true
